services:
  pg:
    image: postgres:latest
    command: postgres -c 'max_connections=250' -c 'shared_buffers=256MB'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password

  pastebin:
    image: kennethreitz/httpbin
    ports:
      - 8081:80
